export const RPC_METHODS = {
    Permission: 'permission',
    Abort: 'abort',
    Switch: 'switch',
    SetSessionConfig: 'set-session-config',
    KillSession: 'killSession',
    HandoffLocal: 'handoff-local',
    SpawnHappySession: 'spawn-happy-session',
    StopSession: 'stop-session',
    StopRunner: 'stop-runner',
    ListMachineDirectory: 'list-directory',
    PathExists: 'path-exists',
    AgentAvailability: 'agent-availability',
    CursorChatStoreStatus: 'cursor-chat-store-status',
    GitStatus: 'git-status',
    GitDiffNumstat: 'git-diff-numstat',
    GitDiffFile: 'git-diff-file',
    ReadFile: 'readFile',
    ReadGeneratedImage: 'readGeneratedImage',
    WriteFile: 'writeFile',
    ListDirectory: 'listDirectory',
    StatFiles: 'statFiles',
    GetDirectoryTree: 'getDirectoryTree',
    UploadFile: 'uploadFile',
    DeleteUpload: 'deleteUpload',
    Ripgrep: 'ripgrep',
    Difftastic: 'difftastic',
    Bash: 'bash',
    ListSlashCommands: 'listSlashCommands',
    ListSkills: 'listSkills',
    ListCodexModels: 'listCodexModels',
    ListPiModelsForMachine: 'listPiModelsForMachine',
    ListCodexSessions: 'listCodexSessions',
    ArchiveCodexSession: 'archiveCodexSession',
    ListCursorModels: 'listCursorModels',
    ListPiModels: 'listPiModels',
    ListPiSessions: 'listPiSessions',
    ListOpencodeModels: 'listOpencodeModels',
    ListOpencodeModelsForCwd: 'listOpencodeModelsForCwd',
    ListGrokModelsForCwd: 'listGrokModelsForCwd',
    ListGrokModels: 'listGrokModels',
    ListGrokReasoningEffortOptions: 'listGrokReasoningEffortOptions',
    ListCopilotModelsForCwd: 'listCopilotModelsForCwd',
    ListCopilotModels: 'listCopilotModels',
    ListOpencodeReasoningEffortOptions: 'listOpencodeReasoningEffortOptions',
    ListAgyModels: 'listAgyModels',
    /** Deliver one queued message into the active Pi turn (native steer). */
    SteerQueuedMessage: 'steer-queued-message',
    ForkConversation: 'fork-conversation',
    RewindConversation: 'rewind-conversation',
} as const

export const RPC_TARGET_MISSING_ERROR_CODE = 'rpc_target_missing' as const

export type RpcMethod = typeof RPC_METHODS[keyof typeof RPC_METHODS]
